### ISSUE TITLE
Setup VS Code environment automatically

### ISSUE THREAD

**Issue by moshekagan** [moshebe/gebug#33]
I had some issues while trying to use the debugger option in visual studio code. I managed to solve it eventually by creating launch.json by myself and assign the remote port that was set by Gebug,  but it would be nice if the init process would setup the environment for me.

Maybe gebug init should ask if its want to set up the required files for this to work. It will be different between IDEs so it should try to figure it out (checking for .vscode, etc...)

**Comment by moshebe** [comment]
Hi @moshekagan,
Thanks for taking the time and writing this issue, it's a really good suggestion.
Just want to let you know that I started working on this feature, would like to share with you the current plan:
- During the `init` process we will try to auto-detect IDEs files (like `.vscode`, `.idea` etc.) and in case of enabling debugger mode, the user will be prompted to confirm editing of the IDE configuration files to auto-configure the IDE's debugger.
- Some command will be added to the CLI in order to manage those IDE:

```
gebug debugger set vscode
gebug debugger unset vscode
gebug debugger list [--only-set --only-unset --all]
```

(set means IDE that was detected in the directory but Gebug was not configured there yet)

Let me know if you another suggestion or correction, I would like to hear!
